name: 部署到服务器

on:
  push:
    branches: ['main']

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: 检出仓库代码
        uses: actions/checkout@v4

      - name: 调试-列出仓库文件
        run: ls -la $GITHUB_WORKSPACE

      - name: 设置SSH环境
        run: |
          mkdir -p ~/.ssh
          chmod 700 ~/.ssh
          echo "${{ secrets.SSH_PRIVATE_KEY }}" | tr -d '\r' > ~/.ssh/github_actions_key
          chmod 600 ~/.ssh/github_actions_key
          ssh-keyscan -p ${{ secrets.SSH_PORT }} ${{ secrets.SERVER_IP }} >> ~/.ssh/known_hosts

      - name: 安装Rsync工具
        run: sudo apt-get update && sudo apt-get install -y rsync

      - name: 同步文件到服务器
        run: |
          rsync -avz --progress --delete \
            --exclude={'/.git','/.github','/node_modules','*.log','.env*'} \
            -e "ssh -i ~/.ssh/github_actions_key -o StrictHostKeyChecking=no -p ${{ secrets.SSH_PORT }}" \
            $GITHUB_WORKSPACE/ \
            ${{ secrets.SSH_USERNAME }}@${{ secrets.SERVER_IP }}:/www/wwwroot/egg-blog/ \
            || echo "忽略非关键错误"

      - name: 重启PM2服务
        run: |
          ssh -i ~/.ssh/github_actions_key -p ${{ secrets.SSH_PORT }} ${{ secrets.SSH_USERNAME }}@${{ secrets.SERVER_IP }} <<'EOF'
          # 加载环境变量
          source ~/.bashrc 2>/dev/null || true
          source ~/.nvm/nvm.sh 2>/dev/null || true

          # 使用绝对路径调用PM2
          PM2_BIN=$(which pm2 || echo "/usr/local/bin/pm2")
          echo "PM2路径: $PM2_BIN"

          # 进程管理
          APP_NAME="egg-blog"
          DEPLOY_PATH="/www/wwwroot/egg-blog"
          
          if $PM2_BIN list | grep -q $APP_NAME; then
            echo "热重启应用..."
            $PM2_BIN reload $APP_NAME --update-env
          else
            echo "冷启动应用..."
            cd $DEPLOY_PATH && $PM2_BIN start ecosystem.config.js
          fi

          # 保存状态
          $PM2_BIN save
          $PM2_BIN logs $APP_NAME --lines 20 --nostream
          EOF

      - name: 部署验证
        if: always()
        run: |
          ssh -i ~/.ssh/github_actions_key -p ${{ secrets.SSH_PORT }} ${{ secrets.SSH_USERNAME }}@${{ secrets.SERVER_IP }} <<'EOF'
          echo "==== 部署验证 ===="
          echo "当前用户: $(whoami)"
          echo "PM2进程列表:"
          pm2 list || which pm2
          echo "项目目录文件:"
          ls -la /www/wwwroot/egg-blog
          EOF

      - name: 强制成功步骤
        if: always()
        run: echo "流程执行完毕，状态码: ${{ job.status }}"