name: 部署到服务器

on:
    push:
        branches: ['main']

jobs:
    deploy:
        runs-on: ubuntu-latest

        steps:
            # ... [保持其他步骤不变] ...

            - name: 重启PM2服务
              run: |
                  ssh -i ~/.ssh/github_actions_key -p ${{ secrets.SSH_PORT }} ${{ secrets.SSH_USERNAME }}@${{ secrets.SERVER_IP }} <<'EOL'
                  # 强制加载环境配置
                  source ~/.bashrc 2>/dev/null || true
                  source ~/.bash_profile 2>/dev/null || true
                  source ~/.profile 2>/dev/null || true

                  # 验证环境路径
                  export PATH="$PATH:/usr/local/bin:$HOME/.npm-global/bin"
                  echo "PM2路径: $(which pm2)"

                  # 重启应用流程
                  PM2_PATH="/www/wwwroot/egg-blog"
                  if pm2 list | grep -q "egg-blog"; then
                    echo "正在重启应用..."
                    pm2 restart egg-blog --update-env
                  else
                    echo "启动新应用..."
                    cd $PM2_PATH && pm2 start ecosystem.config.js
                  fi

                  # 保存配置并输出日志
                  pm2 save
                  pm2 logs --lines 10 --nostream
                  EOL
