name: 部署到服务器

on:
    push:
        branches: ['main']

jobs:
    deploy:
        runs-on: ubuntu-latest

        steps:
            - name: 检出仓库代码
              uses: actions/checkout@v4

            - name: 设置 SSH 环境
              run: |
                  mkdir -p ~/.ssh
                  chmod 700 ~/.ssh
                  echo "${{ secrets.SSH_PRIVATE_KEY }}" | tr -d '\r' > ~/.ssh/github_actions_key
                  chmod 600 ~/.ssh/github_actions_key
                  ssh-keyscan -p ${{ secrets.SSH_PORT }} ${{ secrets.SERVER_IP }} >> ~/.ssh/known_hosts

            - name: 安装 Rsync 工具
              run: sudo apt-get update && sudo apt-get install -y rsync

            - name: 停止 PM2 服务
              run: |
                  ssh -i ~/.ssh/github_actions_key -p ${{ secrets.SSH_PORT }} ${{ secrets.SSH_USERNAME }}@${{ secrets.SERVER_IP }} <<EOF
                  cd /www/wwwroot/egg-blog
                  pm2 stop app || echo "无需停止"
                  pm2 delete app || echo "无需删除"
                  pkill -f "npm start" || echo "无残留进程"
                  EOF

            - name: 清理服务器旧文件（保留node_modules）
              run: |
                  ssh -i ~/.ssh/github_actions_key -p ${{ secrets.SSH_PORT }} ${{ secrets.SSH_USERNAME }}@${{ secrets.SERVER_IP }} <<EOF
                  cd /www/wwwroot/egg-blog
                  # 保留 node_modules 和隐藏文件
                  find . -maxdepth 1 \
                    ! -name 'node_modules' \
                    ! -name '.' \
                    ! -name '..' \
                    -exec rm -rf {} +
                  EOF

            - name: 同步文件到服务器
              run: |
                  rsync -avz --delete --progress \
                    --exclude='node_modules/' \
                    --exclude='*.log' \
                    -e "ssh -i ~/.ssh/github_actions_key -o StrictHostKeyChecking=no -p ${{ secrets.SSH_PORT }}" \
                    $GITHUB_WORKSPACE/ \
                    ${{ secrets.SSH_USERNAME }}@${{ secrets.SERVER_IP }}:/www/wwwroot/egg-blog/

            - name: 启动 PM2 服务
              run: |
                  ssh -i ~/.ssh/github_actions_key -p ${{ secrets.SSH_PORT }} ${{ secrets.SSH_USERNAME }}@${{ secrets.SERVER_IP }} <<EOF
                  cd /www/wwwroot/egg-blog
                  # 检查是否已存在进程
                  if pm2 list | grep -q app; then
                    pm2 reload app --update-env
                  else
                    pm2 start npm --name "app" -- start
                  fi
                  pm2 save
                  # 避免重复设置启动项（建议提前手动设置）
                  # sudo env PATH=$PATH:/www/server/nvm/versions/node/v18.20.8/bin /www/server/nvm/versions/node/v18.20.8/lib/node_modules/pm2/bin/pm2 startup systemd -u ${{ secrets.SSH_USERNAME }} --hp /home/${{ secrets.SSH_USERNAME }}
                  EOF
