name: 部署到服务器

on:
    push:
        branches: ['main']

jobs:
    deploy:
        runs-on: ubuntu-latest

        steps:
            - name: 检出代码
              uses: actions/checkout@v4

            - name: 设置 SSH 环境
              run: |
                  mkdir -p ~/.ssh
                  chmod 700 ~/.ssh
                  echo "${{ secrets.SSH_PRIVATE_KEY }}" | tr -d '\r' > ~/.ssh/github_actions_key
                  chmod 600 ~/.ssh/github_actions_key
                  ssh-keyscan -p ${{ secrets.SSH_PORT }} ${{ secrets.SERVER_IP }} >> ~/.ssh/known_hosts

            - name: 安装 Rsync 工具
              run: sudo apt-get update && sudo apt-get install -y rsync

            - name: 停止 PM2 服务
              run: |
                  ssh -i ~/.ssh/github_actions_key -p ${{ secrets.SSH_PORT }} ${{ secrets.SSH_USERNAME }}@${{ secrets.SERVER_IP }} \
                  "cd /www/wwwroot/egg-blog && pm2 stop all || true && pm2 delete all || true"

            - name: 清空服务器目录（保留空结构）
              run: |
                  ssh -i ~/.ssh/github_actions_key -p ${{ secrets.SSH_PORT }} ${{ secrets.SSH_USERNAME }}@${{ secrets.SERVER_IP }} \
                  "rm -rf /www/wwwroot/egg-blog/* && mkdir -p /www/wwwroot/egg-blog/public/markdownFiles"

            - name: 同步文件到服务器
              run: |
                  rsync -avz --progress \
                    --delete \
                    --exclude='node_modules/' \
                    --exclude='*.log' \
                    --rsync-path="sudo rsync" \
                    --chown=${{ secrets.SSH_USERNAME }}:${{ secrets.SSH_USERNAME }} \
                    -e "ssh -i ~/.ssh/github_actions_key -o StrictHostKeyChecking=no -p ${{ secrets.SSH_PORT }}" \
                    $GITHUB_WORKSPACE/ \
                    ${{ secrets.SSH_USERNAME }}@${{ secrets.SERVER_IP }}:/www/wwwroot/egg-blog/

            - name: 启动 PM2 服务
              run: |
                  ssh -i ~/.ssh/github_actions_key -p ${{ secrets.SSH_PORT }} ${{ secrets.SSH_USERNAME }}@${{ secrets.SERVER_IP }} \
                  "cd /www/wwwroot/egg-blog && pm2 start npm --name 'app' -- start"
