name: 精准部署方案

on:
    push:
        branches: [main]

jobs:
    deploy:
        runs-on: ubuntu-latest

        steps:
            - name: 检出代码
              uses: actions/checkout@v4

            - name: 配置SSH
              run: |
                  mkdir -p ~/.ssh
                  echo "${{ secrets.SSH_PRIVATE_KEY }}" | tr -d '\r' > ~/.ssh/deploy_key
                  chmod 600 ~/.ssh/deploy_key
                  ssh-keyscan -p ${{ secrets.SSH_PORT }} ${{ secrets.SERVER_IP }} >> ~/.ssh/known_hosts

            - name: 安全清理目标目录
              run: |
                  ssh -i ~/.ssh/deploy_key -p ${{ secrets.SSH_PORT }} ${{ secrets.SSH_USERNAME }}@${{ secrets.SERVER_IP }} \
                    "mkdir -p /www/wwwroot/egg-blog || true && \
                     find /www/wwwroot/egg-blog -type d -name 'empty' -delete 2>/dev/null"

            - name: 增强同步（不修改PM2配置）
              run: |
                  rsync -avz --progress \
                    --delete \
                    --exclude='.git' \
                    --exclude='.github' \
                    --exclude='*.log' \
                    --exclude='node_modules/' \
                    --exclude='empty/' \
                    --exclude='*/empty/' \
                    --exclude='.git/objects/' \
                    --filter='- empty*' \
                    -e "ssh -i ~/.ssh/deploy_key -p ${{ secrets.SSH_PORT }}" \
                    $GITHUB_WORKSPACE/ \
                    ${{ secrets.SSH_USERNAME }}@${{ secrets.SERVER_IP }}:/www/wwwroot/egg-blog/

            - name: 重启PM2服务（保持原配置）
              run: |
                  ssh -i ~/.ssh/deploy_key -p ${{ secrets.SSH_PORT }} ${{ secrets.SSH_USERNAME }}@${{ secrets.SERVER_IP }} \
                    "cd /www/wwwroot/egg-blog && \
                     if pm2 list | grep -q 'egg-blog'; then \
                       pm2 reload ecosystem.config.js --update-env; \
                     else \
                       pm2 start ecosystem.config.js; \
                     fi; \
                     pm2 save"
