name: 部署到服务器

on:
    push:
        branches: ['main']

jobs:
    deploy:
        runs-on: ubuntu-latest

        steps:
            - name: 检出仓库代码
              uses: actions/checkout@v4

            - name: 设置 SSH 环境
              run: |
                  mkdir -p ~/.ssh
                  chmod 700 ~/.ssh
                  echo "${{ secrets.SSH_PRIVATE_KEY }}" | tr -d '\r' > ~/.ssh/github_actions_key
                  chmod 600 ~/.ssh/github_actions_key
                  ssh-keyscan -p ${{ secrets.SSH_PORT }} ${{ secrets.SERVER_IP }} >> ~/.ssh/known_hosts

            - name: 强制终止旧进程
              run: |
                  ssh -i ~/.ssh/github_actions_key -p ${{ secrets.SSH_PORT }} ${{ secrets.SSH_USERNAME }}@${{ secrets.SERVER_IP }} \
                  << 'EOF'
                  pkill -9 -f 'node /www/wwwroot/egg-blog/app.js'
                  pm2 kill -f || true
                  rm -rf /www/wwwroot/egg-blog/.pm2
                  EOF

            - name: 同步代码（含PM2配置）
              run: |
                  rsync -avz --progress \
                    --delete \
                    --exclude='node_modules/' \
                    --exclude='*.log' \
                    --exclude='.env*' \
                    --include='.env.production' \
                    --include='ecosystem.config.js'  # 确保同步配置文件
                    -e "ssh -i ~/.ssh/github_actions_key -o StrictHostKeyChecking=no -p ${{ secrets.SSH_PORT }}" \
                    $GITHUB_WORKSPACE/ \
                    ${{ secrets.SSH_USERNAME }}@${{ secrets.SERVER_IP }}:/www/wwwroot/egg-blog/

            - name: 创建PM2配置文件（双重保障）
              run: |
                  ssh -i ~/.ssh/github_actions_key -p ${{ secrets.SSH_PORT }} ${{ secrets.SSH_USERNAME }}@${{ secrets.SERVER_IP }} \
                  "mkdir -p /www/wwwroot/egg-blog && \
                  [ ! -f /www/wwwroot/egg-blog/ecosystem.config.js ] && \
                  echo 'module.exports = {
                    apps: [{
                      name: \"app\",
                      script: \"./app.js\",
                      cwd: \"/www/wwwroot/egg-blog\",
                      error_file: \"logs/err.log\",
                      out_file: \"logs/out.log\",
                      autorestart: true,
                      max_memory_restart: \"1G\",
                      env_production: {
                        NODE_ENV: \"production\"
                      }
                    }]
                  }' > /www/wwwroot/egg-blog/ecosystem.config.js"

            - name: 重启服务（增强版）
              run: |
                  ssh -i ~/.ssh/github_actions_key -p ${{ secrets.SSH_PORT }} ${{ secrets.SSH_USERNAME }}@${{ secrets.SERVER_IP }} \
                  << 'EOF'
                  # 等待文件完全同步
                  sleep 3

                  # 检查配置文件有效性
                  if ! pm2 list | grep -q app; then
                    pm2 start /www/wwwroot/egg-blog/ecosystem.config.js --env production
                  else
                    pm2 reload app --update-env
                  fi

                  # 清理旧日志
                  pm2 flush
                  EOF
