name: 强制部署到服务器

on:
  push:
    branches: ['main']

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: 设置SSH环境
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_PRIVATE_KEY }}" | tr -d '\r' > ~/.ssh/github_actions_key
          chmod 600 ~/.ssh/github_actions_key
          ssh-keyscan -p ${{ secrets.SSH_PORT }} ${{ secrets.SERVER_IP }} >> ~/.ssh/known_hosts

      - name: 停止远程服务
        run: |
          ssh -i ~/.ssh/github_actions_key -p ${{ secrets.SSH_PORT }} ${{ secrets.SSH_USERNAME }}@${{ secrets.SERVER_IP }} \
            "sudo systemctl stop nginx php-fpm || echo '无需停止服务'"

      - name: 强制同步文件
        run: |
          rsync -avz --progress --delete --force \
            --exclude='.git' \
            --exclude='*.lock' \
            --exclude='node_modules/' \
            -e "ssh -i ~/.ssh/github_actions_key -p ${{ secrets.SSH_PORT }}" \
            $GITHUB_WORKSPACE/ \
            ${{ secrets.SSH_USERNAME }}@${{ secrets.SERVER_IP }}:/www/wwwroot/egg-blog/

      - name: 重启远程服务
        run: |
          ssh -i ~/.ssh/github_actions_key -p ${{ secrets.SSH_PORT }} ${{ secrets.SSH_USERNAME }}@${{ secrets.SERVER_IP }} \
            "sudo systemctl start nginx php-fpm"
