name: 部署到服务器

on:
    push:
        branches: ['main']

jobs:
    deploy:
        runs-on: ubuntu-latest

        steps:
            - name: 检出仓库代码
              uses: actions/checkout@v4

            - name: 调试-列出仓库文件
              run: ls -la $GITHUB_WORKSPACE

            - name: 设置SSH环境
              run: |
                  mkdir -p ~/.ssh
                  chmod 700 ~/.ssh
                  echo "${{ secrets.SSH_PRIVATE_KEY }}" | tr -d '\r' > ~/.ssh/github_actions_key
                  chmod 600 ~/.ssh/github_actions_key
                  ssh-keyscan -p ${{ secrets.SSH_PORT }} ${{ secrets.SERVER_IP }} >> ~/.ssh/known_hosts

            - name: 安装Rsync工具
              run: sudo apt-get update && sudo apt-get install -y rsync

            - name: 同步文件到服务器
              run: |
                  rsync -avz --progress \
                    --exclude='.git' \
                    --exclude='.github/' \
                    --exclude='node_modules/' \
                    --exclude='*.log' \
                    -e "ssh -i ~/.ssh/github_actions_key -o StrictHostKeyChecking=no -p ${{ secrets.SSH_PORT }}" \
                    $GITHUB_WORKSPACE/ \
                    ${{ secrets.SSH_USERNAME }}@${{ secrets.SERVER_IP }}:/www/wwwroot/egg-blog/ \
                    || echo "忽略非关键错误"  # 错误抑制

            - name: 强制成功步骤
              if: always() # 无论上一步是否失败都执行
              run: echo "强制继续执行流程..."

            - name: 调试-列出目标目录文件
              run: |
                  ssh -i ~/.ssh/github_actions_key -p ${{ secrets.SSH_PORT }} ${{ secrets.SSH_USERNAME }}@${{ secrets.SERVER_IP }} \
                    "ls -la /www/wwwroot/egg-blog"

            - name: 重启 PM2 服务
              run: |
                  ssh -i ~/.ssh/github_actions_key -p ${{ secrets.SSH_PORT }} ${{ secrets.SSH_USERNAME }}@${{ secrets.SERVER_IP }} \
                    "pm2 restart all"
