name: 部署Node.js后端代码到服务器

on:
  push:
    branches: [ "main" ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: 检出代码
      uses: actions/checkout@v4

    - name: 清理Git元数据
      run: |
        # 删除.git目录和残留文件
        rm -rf .git
        find . -name '.git*' -exec rm -rf {} +

    - name: 配置SSH环境
      run: |
        mkdir -p ~/.ssh
        chmod 700 ~/.ssh
        echo "${{ secrets.SSH_PRIVATE_KEY }}" | tr -d '\r' > ~/.ssh/github_actions_key
        chmod 600 ~/.ssh/github_actions_key
        ssh-keyscan -p ${{ secrets.SSH_PORT }} ${{ secrets.SERVER_IP }} >> ~/.ssh/known_hosts

    - name: 安装Rsync
      run: sudo apt-get update && sudo apt-get install -y rsync

    - name: 预同步目录结构
      run: |
        rsync -avzvv --progress \
          --include='*/' \
          --exclude='*' \
          -e "ssh -i ~/.ssh/github_actions_key -p ${{ secrets.SSH_PORT }}" \
          ./ \
          ${{ secrets.SSH_USERNAME }}@${{ secrets.SERVER_IP }}:/www/wwwroot/egg-blog/

    - name: 智能同步核心文件
      run: |
        rsync -avzvv --delay-updates --progress --delete \
          --exclude='node_modules/' \
          --exclude='.git/' \
          --exclude='.github/' \
          --filter=':- .gitignore' \
          --chmod=D755,F644 \
          -e "ssh -i ~/.ssh/github_actions_key -p ${{ secrets.SSH_PORT }}" \
          ./ \
          ${{ secrets.SSH_USERNAME }}@${{ secrets.SERVER_IP }}:/www/wwwroot/egg-blog/
      
    - name: 防御性权限修复
      run: |
        ssh -i ~/.ssh/github_actions_key -p ${{ secrets.SSH_PORT }} ${{ secrets.SSH_USERNAME }}@${{ secrets.SERVER_IP }} \
          "find /www/wwwroot/egg-blog/ -type d -exec chmod 755 {} \; && \
           find /www/wwwroot/egg-blog/ -type f -exec chmod 644 {} \; && \
           chown -R www-data:www-data /www/wwwroot/egg-blog/ && \
           systemctl restart nginx"
